#!/usr/bin/env python

import rospy
import time
import os
from std_msgs.msg import String
from sensor_msgs.msg import JointState


def callback(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)


def callback2(data):
    rospy.loginfo(data)


if __name__ == '__main__':
    rospy.init_node('control', anonymous=False)
    rate = rospy.Rate(50)
    sub2 = rospy.Subscriber("/simulation/joint_state", JointState, callback2)
    pub = rospy.Publisher("~command", String, queue_size=1)

    k = 0
    start = time.time()
    while not rospy.is_shutdown():
        now = time.time()
        pub.publish("hello")
        elapsed = time.time() - now
        k = k + 1
        # rospy.loginfo("Average rate: %s" % (k / (time.time() - start)))
        rate.sleep()
