#!/usr/bin/env python

import os
import time
import signal
import quaternion
import sys

from robots import BulletRobot
from simulation import Simulation
from simulation.worlds import EmptyWorld

from pybullet_interfaces import FrankaROSInterface

if __name__ == '__main__':
    interface = FrankaROSInterface()

    desired_frequency = 500.0
    # create simulation object
    simulation = Simulation(realtime_sim=False, realtime_sim_freq=desired_frequency)

    # load empty world and add table
    world = EmptyWorld(uid=simulation.uid, add_plane=True, gravity=[0, 0, -9.81])
    world.add_object_from_urdf('table', 'table/table.urdf', position_xyz=[0.4, 0, 0],
                               orientation_wxyz=[0, 0, -0.707, 0.707], fixed_base=True, scaling=0.5)

    # create robot after adding models path
    # if not simulation.add_robot_models_path(os.path.join(os.path.dirname(__file__), os.pardir, "models/panda")):
    #     exit(1)
    robot = BulletRobot(robot_urdf="/home/ros/ros_ws/src/pybullet_interfaces/models/panda/panda_arm.urdf",
                        enforce_joint_limits=False, uid=simulation.uid)
    # Test some bullet_robot_description methods
    robot.set_default_joint_positions([-0.017792060227770554, -0.7601235411041661, 0.019782607023391807,
                                       -2.342050140544315, 0.029840531355804868, 1.5411935298621688,
                                       0.7534486589746342])
    robot.goto_default_joint_positions()
    robot.set_control_mode('torque')
    robot.enable()

    time.sleep(1)
    command = [0, 0, 0, 0, 0, 0, 0]
    first_command_received = False
    start = time.time()
    k = 0
    while simulation.is_alive():
        now = time.time()
        state = robot.get_state()

        interface.publish_robot_state(state)
        command = interface.get_command()
        if command:
            # print(command)
            robot.set_joint_torques_cmd(command, compensate_gravity=True)
        else:
            robot.set_joint_torques_cmd([0] * 7, compensate_gravity=True)
            print(k)
        # print(state.joint_positions, state.joint_velocities)
        # print(state.ee_position, quaternion.as_float_array(state.ee_orientation))

        simulation.step()

        elapsed = time.time() - now
        sleep_time = (1. / desired_frequency) - elapsed
        if sleep_time > 0.0:
            time.sleep(sleep_time)
        k = k + 1

    # print("Average rate: ", k / (time.time() - start))
